services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_view_table
    ports:
      - "8000:8000"
    volumes:
      - /var/www/html
    environment:
      APP_ENV: local
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
